### PR TITLE
Manually set PATH and VIRTUAL_ENV for all binder related files

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref https://github.com/rocker-org/rocker-versioned2/issues/739

### CODE REVIEW

**Review by eitsupi — APPROVED** [review]
Thanks for doing this!

**Comment by cboettig** [comment]
nice, thanks both!

**Comment by yuvipanda** [comment]
Thanks @cboettig! Will this trigger a rebuild?

**Comment by cboettig** [comment]
I triggered manual dispatch https://github.com/rocker-org/rocker-versioned2/actions/runs/7359142000

**Pull request merged**
