### PR TITLE
Patch/gdal

### PR DESCRIPTION
**Pull request by cboettig**

### CODE REVIEW

**Comment by eitsupi** [comment]
The Dockerfile must also be updated.

Could you also confirm the contents of #455?

**Comment by cboettig** [comment]
Thanks - isn't the Dockerfile updated automatically by the script though?  Or should I run `./build/make-stacks.R` locally?

Workflow-wise, would it be easier to fold these changes into #455 ?

**Comment by eitsupi** [comment]
Yeah, unfortunately for now the Dockerfile won't update unless you do `make setup` locally...

If you are willing, I would like to take the content of this PR and revise it together with #455.
I am going to bed today but will try to finish #455 tomorrow so that we can merge and build.

**Comment by cboettig** [comment]
@eitsupi sounds like a plan, thank you! I'll close this and thanks for folding it into #455

**Pull request closed without merging**
