### PR TITLE
turn off for `rocker/verse` devel build that is currently failing

### PR DESCRIPTION
**Pull request by cboettig**
turn of cron job that is currently failing

### CODE REVIEW

**Comment by eitsupi** [comment]
Why do you want to do this?
And why don't you change it so that you don't only build `verse`, since it seems to be only `verse` is failing?

**Comment by cboettig** [comment]
@eitsupi thanks, good idea!

**Comment by cboettig** [comment]
better?

**Review by eitsupi — APPROVED** [review]
I think that makes sense.

**Comment by eitsupi** [comment]
Do you know why the rocker/verse build is failing in the first place? The log shows the following:

<details>
<summary>Details</summary>

```log
#30 292.3 * installing *source* package ‘rJava’ ...
#30 292.3 ** package ‘rJava’ successfully unpacked and MD5 sums checked
#30 292.3 ** using staged installation
#30 292.3 checking for gcc... gcc
#30 292.3 checking whether the C compiler works... yes
#30 292.3 checking for C compiler default output file name... a.out
#30 292.3 checking for suffix of executables... 
#30 292.3 checking whether we are cross compiling... no
#30 292.3 checking for suffix of object files... o
#30 292.3 checking whether we are using the GNU C compiler... yes
#30 292.3 checking whether gcc accepts -g... yes
#30 292.3 checking for gcc option to accept ISO C89... none needed
#30 292.3 checking how to run the C preprocessor... gcc -E
#30 292.3 checking for grep that handles long lines and -e... /usr/bin/grep
#30 292.3 checking for egrep... /usr/bin/grep -E
#30 292.3 checking for ANSI C header files... yes
#30 292.3 checking for sys/wait.h that is POSIX.1 compatible... yes
#30 292.3 checking for sys/types.h... yes
#30 292.3 checking for sys/stat.h... yes
#30 292.3 checking for stdlib.h... yes
#30 292.3 checking for string.h... yes
#30 292.3 checking for memory.h... yes
#30 292.3 checking for strings.h... yes
#30 292.3 checking for inttypes.h... yes
#30 292.3 checking for stdint.h... yes
#30 292.3 checking for unistd.h... yes
#30 292.3 checking for string.h... (cached) yes
#30 292.3 checking sys/time.h usability... yes
#30 292.3 checking sys/time.h presence... yes
#30 292.3 checking for sys/time.h... yes
#30 292.3 checking for unistd.h... (cached) yes
#30 292.3 checking for an ANSI C-conforming const... yes
#30 292.3 checking whether time.h and sys/time.h may both be included... yes
#30 292.3 configure: checking whether gcc supports static inline...
#30 292.3 yes
#30 292.3 checking whether setjmp.h is POSIX.1 compatible... yes
#30 292.3 checking whether sigsetjmp is declared... yes
#30 292.3 checking whether siglongjmp is declared... yes
#30 292.3 checking Java support in R... present:
#30 292.3 interpreter : '/usr/bin/java'
#30 292.3 archiver    : '/usr/bin/jar'
#30 292.3 compiler    : '/usr/bin/javac'
#30 292.3 header prep.: ''
#30 292.3 cpp flags   : '-I/usr/lib/jvm/java-21-openjdk-amd64/include -I/usr/lib/jvm/java-21-openjdk-amd64/include/linux'
#30 292.3 java libs   : '-L/usr/lib/jvm/java-21-openjdk-amd64/lib/server -ljvm'
#30 292.3 checking whether Java run-time works... ./configure: line 3796: /usr/bin/java: No such file or directory
#30 292.3 no
#30 292.3 configure: error: Java interpreter '/usr/bin/java' does not work
#30 292.3 ERROR: configuration failed for package ‘rJava’
#30 292.3 * removing ‘/usr/local/lib/R/site-library/rJava’
#30 292.3 
#30 292.3 The downloaded source packages are in
#30 292.3 	‘/tmp/downloaded_packages’
#30 292.3 Error: installation of package ‘rJava’ failed
#30 292.3 In addition: Warning messages:
#30 292.3 1: package ‘rmdshower’ is not available for this version of R
#30 292.3 
#30 292.3 A version of this package for your version of R might be available elsewhere,
#30 292.3 see the ideas at
#30 292.3 https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#Installing-packages 
#30 292.3 2: In install.packages(pkgs, ...) : installation of package ‘rJava’ failed
#30 ERROR: process "/bin/sh -c /rocker_scripts/install_verse.sh" did not complete successfully: exit code: 1
------
 > [22/23] RUN /rocker_scripts/install_verse.sh:
292.3 The downloaded source packages are in
292.3 	‘/tmp/downloaded_packages’
292.3 Error: installation of package ‘rJava’ failed
292.3 In addition: Warning messages:
292.3 1: package ‘rmdshower’ is not available for this version of R
292.3 
292.3 A version of this package for your version of R might be available elsewhere,
292.3 see the ideas at
292.3 https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#Installing-packages 
292.3 2: In install.packages(pkgs, ...) : installation of package ‘rJava’ failed
------
verse_devel.Dockerfile:46
--------------------
  44 |     COPY scripts/install_verse.sh /rocker_scripts/install_verse.sh
  45 |     COPY scripts/install_texlive.sh /rocker_scripts/install_texlive.sh
  46 | >>> RUN /rocker_scripts/install_verse.sh
  47 |     
  48 |     COPY scripts /rocker_scripts
--------------------
ERROR: failed to solve: process "/bin/sh -c /rocker_scripts/install_verse.sh" did not complete successfully: exit code: 1
make: *** [Makefile:49: bake-json/verse] Error 1
Error: Process completed with exit code 2.
```

</details>

**Comment by benz0li** [comment]
@eitsupi Then remove it.

It has been archived for a long time: https://cran.r-project.org/web//packages//rmdshower/index.html

**Comment by eitsupi** [comment]
Thank you. But the option to ignore non-existent packages is enabled, so that should not be the cause of the build failure.
I think the problem is `rJava` installation failure.

**Comment by benz0li** [comment]
> Thank you. But the option to ignore non-existent packages is enabled, so that should not be the cause of the build failure.

Agreed.

> I think the problem is `rJava` installation failure.

Yes. Because of `default-jdk` installing OpenJDK 21?

Are you on Ubuntu 22.04 or 24.04?

**Comment by benz0li** [comment]
https://hub.docker.com/_/ubuntu: `ubuntu:latest` = `ubuntu:24.04`

**Pull request merged**
