### PR TITLE
Support installing RStudio Server for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by eitsupi**
Related to #282

It appears that `ubuntu:jammy` needs to install a different build of RStudio, which not for `ubuntu:bionic` and `ubuntu:focal`.
https://github.com/rstudio/rstudio/issues/9854#issuecomment-1112568060

### CODE REVIEW

**Comment by eitsupi** [comment]
I'm going to merge it into the default branch at the same time I make changes to the other scripts, so I'll merge it into the working branch once.

**Comment by ShichenXie** [comment]
I'm trying to install the Rstudio-Server in ubuntu 22.04 using this script. However, facing the following error 'libc6-i386 : Depends: libc6 (= 2.31-0ubuntu9.9) but 2.35-0ubuntu3.1 is to be installed'.

**Comment by eitsupi** [comment]
@ShichenXie Hi, this PR was merged over a year ago, so if you are experiencing problems, could you please create a new issue?
Thanks.

**Comment by ShichenXie** [comment]
> @ShichenXie Hi, this PR was merged over a year ago, so if you are experiencing problems, could you please create a new issue? Thanks.

OK, thanks.

**Pull request merged**
