### PR TITLE
Add `Versions.md` to the wiki

### PR DESCRIPTION
**Pull request by eitsupi**
Related to #201

Now that #328 has been merged, we can generate a table to see the list of configuration values for each version, like https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md
I think it would be useful if this could be registered in the wiki and automatically updated.

### Versions.md

image

### sidebar

image

**ToDo**

- [x] Add sidebar of the wiki
- [x] Update the job to update wiki
- [x] Update `build/README.md` (About the disappearance of the corresponding version from `Versions.md` when the stackfile is deleted)

### CODE REVIEW

**Comment by behrica** [comment]
I am just trying a Dockerfile with simply having:

```
FROM rocker/rstudio:4.0.3
RUN Rscript -e 'install.packages(c("httr","rlist","dplyr","purrr","stringr","AzureTableStor","lubridate","uuid"))'
RUN Rscript -e 'install.packages(c("rjson","tidyr"))'
```

and I get some unexpected warnings: that packes were compile wth R 4.0.5 (while the image tag I use is 4.0.3).
This seems strange to me ?

Additionally the date in the repository is "not matching"  your table above:

```
getOption("repos")
                                                                CRAN 
"https://packagemanager.rstudio.com/cran/__linux__/focal/2021-02-17" 
```

Is this expected ?

**Comment by eitsupi** [comment]
https://www.rocker-project.org/use/extending/

You may find this page helpful. For example, if you build an image from the following Dockerfile, you can modify CRAN and install the package.

```Dockerfile
FROM rocker/rstudio:4.0.3

RUN echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/focal/2021-02-11"))' >> ${R_HOME}/etc/Rprofile.site

RUN install2.r --error --skipinstalled --ncpus -1 httr rlist dplyr purrr stringr AzureTableStor lubridate uuid rjson tidyr
```

**Comment by eitsupi** [comment]
I'm done editing, but for the next few months (until the release of R4.1.3) the CRAN dates will continue to be inconsistent between this document and the container images we can pull from DockerHub, so do you think it might be better not to merge until the release of R4.1.3?

**Comment by eitsupi** [comment]
I will merge this when R 4.1.3 is released.

**Pull request merged**
