### PR TITLE
[CI] Fix and refactor the script to auto update definition files

### PR DESCRIPTION
**Pull request by eitsupi**
- Fix a process that started to fail due to the announcement of Ubuntu 24.04.
- Use short URLs `p3m.dev/cran` for Posit Public Package Manager, which have recently come into use.

### CODE REVIEW

**Comment by eitsupi** [comment]
Super Linter failure on CI is unrelated to this change.

**Comment by eitsupi** [comment]
@cboettig Could you check this?

**Comment by cboettig** [comment]
nice this is working for me!

**Comment by eitsupi** [comment]
Thanks. Merging.

**Pull request merged**
